isi_payslip_email/isi_payslip_email/urls.py
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'', include('webapp.urls')),
    url(r'^payslip/', include("payslip.urls")),
    url(r'^admin/', include(admin.site.urls))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

isi_payslip_email/payslip/urls.py
from __future__ import absolute_import
from django.conf.urls import include, url, patterns


from .views import (Home, EmployeeView, PayslipSendView, PayslipUploadView,
                    MissingUploadedEmployeeAPIView, EmployeeProfile, PayslipSendAPIView,
                    FolderContent, LogUploadedSendPayslipAPIView, LogUploadedSendPayslipView,
                    SearchPayslipAPIView)

urlpatterns = patterns("",
                       url(r'^$', Home.as_view(), name='home'),
                       url(r'^employee/$', EmployeeView.as_view(), name='employee'),
                       url(r'employee/id(/(?P<id>(\d+)))?/?', EmployeeProfile.as_view(), name='employee_profile'),
                       url(r'folder/content/$', FolderContent.as_view(), name='folder_content'),
                       url(r"^send/?$", PayslipSendView.as_view(), name="send-payslip"),
                       url(r"^upload/?$", PayslipUploadView.as_view(), name="upload-payslip")
                       )
# api
urlpatterns += patterns('',
                        url(r"^api/search/$", SearchPayslipAPIView.as_view(),
                            name='search_payslip'),
                        url(r"^api/missing_employee/$", MissingUploadedEmployeeAPIView.as_view(),
                            name='missing_employees'),
                        url(r"^api/send/$", PayslipSendAPIView.as_view(),
                            name='send_email_payslip'),
                        url(r"^api/logs/upload_sent/$", LogUploadedSendPayslipAPIView.as_view(),
                            name='logs_upload_sent_api'),
                        )
# logs
urlpatterns += patterns('',
                        url(r"^logs/upload_sent/$", LogUploadedSendPayslipView.as_view(),
                            name='logs_upload_sent'),
                        url(r"^logs/upload_sent/export/?$", LogUploadedSendPayslipAPIView.as_view(),
                            name='logs_upload_sent_export')
                        )

isi_payslip_email/webapp/urls.py
from django.conf.urls import patterns, include, url

from .views import HomeView

urlpatterns = patterns('',
                        url(r'^$', HomeView.as_view(), name='home'),
                        url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
                        url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': 'login'})
            )

isi_payslip_email/payslip/models.py
import os
from django.db import models
from django.core.files.storage import FileSystemStorage


class OverwritePayslipStorage(FileSystemStorage):
    def _save(self, name, content):
        if self.exists(name):
            self.delete(name)
        return super(OverwritePayslipStorage, self)._save(name, content)

    def get_available_name(self, name):
        return name


def upload_payslip_holder(model_instance, filename):
    return os.path.join(model_instance.payslip_folder.name, filename)



class Employee(models.Model):

    name = models.CharField('Employee Name', max_length=1064, null=False)
    email = models.EmailField('Email')
    active = models.BooleanField('Is Active', default=False)
    send_email = models.BooleanField('Send Email', default=False)
    cc_email = models.EmailField('CC Email')

    def __str__(self):
        return self.name


class PayslipFolder(models.Model):
    name = models.CharField(max_length=255, null=False, unique=True)
    created = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)
    total_uploaded = models.IntegerField(default=0)
    total_sent = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Payslip(models.Model):

    employee = models.ForeignKey(Employee)
    payslip_folder = models.ForeignKey(PayslipFolder)
    filename = models.FileField('Payslip Filename', default='', upload_to=upload_payslip_holder,
                                storage=OverwritePayslipStorage())
    status = models.BooleanField(default=False)
    date_release = models.DateTimeField('Date Release', default=None)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.employee.name

isi_payslip_email/payslip/forms.py
from os import path, listdir
from django import forms
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from datetime import datetime

from .models import Payslip, PayslipFolder

def get_payslip_choices():
    # you place some logic here
    payslip_folder = PayslipFolder.objects.filter(status=False)
    if payslip_folder:
        return [[p.id, p.name] for p in payslip_folder]

    return []


class SendPayslipForm(forms.Form):

    payslip_path = forms.ChoiceField(choices=get_payslip_choices())

    def __init__(self, *args, **kwargs):
        super(SendPayslipForm, self).__init__(*args, **kwargs)
        self.fields['payslip_path'] = forms.ChoiceField(
            choices=get_payslip_choices())

isi_payslip_email/payslip/views.py
from __future__ import absolute_import

import re
from os.path import join
from datetime import date, timedelta
from datetime import datetime
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.views.generic import FormView, TemplateView, ListView
from django.conf import settings
from django.http import JsonResponse

from constance import config

from utils.api import GenericAPIView
from utils.export import exportDataAsExcelFile
from .forms import SendPayslipForm
from .models import Employee, Payslip, PayslipFolder


class Home(TemplateView):
    template_name = 'home.html'


class EmployeeView(TemplateView):
    template_name = 'employee/table.html'

    def get_context_data(self, **kwargs):
        context = super(EmployeeView, self).get_context_data(**kwargs)
        context['table'] = True

        make_emp = lambda u: {'id':u.id, 'name': u.name, 'email': u.email,
                               'active': u.active, 'send_email': u.send_email,
                               'cc_email': u.cc_email}


        emp = Employee.objects.all()
        context['emp'] = [ make_emp(e) for e in emp ]

        return context

class EmployeeProfile(TemplateView):
    template_name = 'employee/profile.html'

    def get_context_data(self, id, **kwargs):
        context = super(EmployeeProfile, self).get_context_data(**kwargs)
        emp = Employee.objects.get(id=id)
        pslips = Payslip.objects.filter(employee=id)
        context['payslips'] = []
        if pslips:
            for p in pslips:
                release = p.date_release
                if not p.status:
                    release = ''
                context['payslips'].append({'name': p.filename.name, 'date': release, 'id': p.pk,
                                            'created': p.created, 'file_url': p.filename.url })

        context['emp'] = {'name' : emp.name, 'email' : emp.email, 'active' : emp.active}
        return context


class PayslipSendView(FormView):
    template_name = 'payslip/index.html'
    template_name_sent = 'payslip/success_email_payslip.html'
    form_class = SendPayslipForm
    success_url = 'payslip/send/'


class FolderContent(GenericAPIView):
    def post(self, request, **kwargs):
        id = int(request.POST.get('id'))
        pslips = Payslip.objects.filter(payslip_folder_id=id)
        data = []
        if pslips:
            for p in pslips:
                user = {
                    'payslip_id': p.pk,
                    'name': p.employee.name,
                    'email': p.employee.email,
                    'filename': p.filename.name,
                    'file_url': p.filename.url,
                    'active': p.employee.active,
                    'send_email': p.employee.send_email,
                    'status': p.status
                }
                data.append(user)

        return JsonResponse(data=data, safe=False)

class PayslipUploadView(TemplateView):
    template_name = 'payslip/upload.html'

    def post(self, request):
        data = request.FILES['files[]']

        filename = data.name
        split_name = filename.split(config.PAYSLIP_PATH_SEPARATOR)

        response = {
            'status': 'error',
            'filename': filename,
            'message': ''
        }
        check = True
        if not filename.endswith('.pdf'):
            check = False
            response.update({'message': 'Invalid File Format.'})

        if len(split_name) != 2:
            check = False
            response.update({'message': 'Invalid Filename Format.'})

        if check:
            pf_name = split_name[0].strip()
            e_name = re.sub('.pdf', '', split_name[1]).strip()

            try:
                employee = Employee.objects.get(name=e_name)
            except Employee.DoesNotExist:
                response.update({'message': 'No Employee Found.'})
            else:
                payslip_folder, created = PayslipFolder.objects.get_or_create(name=pf_name)

                precord = {'employee': employee, 'filename': data, 'payslip_folder': payslip_folder,
                           'date_release': datetime.now(), 'status': False}
                payslip, p_created = Payslip.objects.update_or_create(employee=employee, payslip_folder=payslip_folder,
                                                                      defaults=precord)
                if p_created:
                    payslip_folder.total_uploaded = Payslip.objects.filter(payslip_folder=payslip_folder).count()
                payslip_folder.status = False
                payslip_folder.save()
                data = {
                    'payslip_name': pf_name,
                    'payslip_id': payslip.pk,
                    'name': payslip.employee.name,
                    'filename': payslip.filename.name,
                    'file_url': payslip.filename.url,
                    'active': payslip.employee.active,
                    'send_email': payslip.employee.send_email,
                    'status': payslip.status
                }
                response.update({'status': 'ok', 'message': 'success', 'data': data})

        return JsonResponse(response)


class MissingUploadedEmployeeAPIView(GenericAPIView):

    allowed_methods = ['GET', ]

    def get(self, request, *args, **kwargs):
        response = {
            'status': 'error',
            'message': 'Request Invalid.',
            'data': {}
        }
        data = request.query_params
        pf_name = data.get('payslip', None)
        if pf_name:
            try:
                payslip_folder = PayslipFolder.objects.get(name=pf_name)
            except PayslipFolder.DoesNotExist:
                response.update({'message': 'No Payslip Found.'})
            else:
                employee_ids = Payslip.objects.values_list('employee_id').filter(payslip_folder=payslip_folder)
                employees = Employee.objects.filter(active=True, send_email=True).exclude(pk__in=employee_ids)
                response.update({'status': 'ok', 'message': 'success', 'data': [e.name for e in employees]})

        return JsonResponse(response)


class SearchPayslipAPIView(GenericAPIView):
    allowed_methods = ['GET', ]

    def get(self, request, *args, **kwargs):
        response = {
            'status': 'error',
            'message': 'Request Invalid.',
            'data': {}
        }
        data = request.query_params
        pf_name = data.get('payslip', None)
        if pf_name:
            payslips = PayslipFolder.objects.values_list('pk', 'name').filter(name__icontains=pf_name)
            # http://127.0.0.1:8000/payslip/api/search/?payslip=2015 sample
            # response format
            # {
            #   status: "ok",
            #   message: "success",
            #   data: [ [1,"2015-05-01-15"], [2,"2015-06-01-15"]],....
            # }
            # data = [[id, name], ...]
            response.update({'status': 'ok', 'message': 'success', 'data': list(payslips)})
        return JsonResponse(response)


class PayslipSendAPIView(GenericAPIView):
    allowed_methods = ['POST']

    def post(self, request, *args, **kwargs):
        response = {
            'status': 'error',
            'message': 'Request Invalid',
            'data': {}
        }
        data = request.data
        pid = data.get('pid', None)
        try:
            payslip = Payslip.objects.get(pk=pid)
        except Payslip.DoesNotExist:
            response.update({'message': 'No Payslip Record Found.'})
        else:
            payslip_name = payslip.payslip_folder.name
            # check format YYYY-MM-DD-DD
            if re.match(r'\d{4}-\d{2}-\d{2}-\d{2}', payslip_name):
                ps_name = payslip.payslip_folder.name.split('-')
                d = date(int(ps_name[0]), int(ps_name[1]), int(ps_name[2]))
                month_str = d.strftime('%B')
                payslip_name = '{0} {1}-{2}, {3}'.format(month_str, ps_name[2], ps_name[3], ps_name[0])

            greetings = config.EMAIL_GREETINGS.format(employee_name=payslip.employee.name, payslip_name=payslip_name)
            c_message = config.EMAIL_BODY_MESSAGES.format(employee_name=payslip.employee.name, payslip_name=payslip_name)
            body_message = render_to_string('payslip/send_payslip_message.html', {'logo_url': config.EMAIL_COMPANY_LOGO,
                                                                                  'disclaimer': config.EMAIL_TEMPLATE_DISCLAIMER,
                                                                                  'company_name': config.COMPANY,
                                                                                  'company_address': config.COMPANY_ADDRESS,
                                                                                  'company_site': config.COMPANY_SITE,
                                                                                  'company_phone': config.COMPANY_PHONE,
                                                                                  'greetings': greetings,
                                                                                  'body_message': c_message})

            email = EmailMultiAlternatives(subject='Payslip {}'.format(payslip_name), body=body_message,
                                           from_email=config.COMPANY_EMAIL, to=[payslip.employee.email],
                                           bcc=[payslip.employee.cc_email])
            email.content_subtype = 'html'
            payslip_employee_pdf = join(settings.MEDIA_ROOT, payslip.filename.path)
            email.attach_file(payslip_employee_pdf, 'application/pdf')
            email.attach_alternative(body_message, 'text/html')
            if email.send(fail_silently=False):
                payslip.date_release = datetime.now()
                payslip.status = True
                payslip.save()

isi_payslip_email/payslip/templates/payslip/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}

    <title>Payslip - Send Email</title>

{% endblock head %}

{% block content %}

    <div class="send-form">

        <div id="payslip-select-form">
            {% csrf_token %}
            <input id="id_payslip_path"
                   class="form-control"
                   type="text"
                   placeholder="Type here: 2016">
            <div class="glyphicon glyphicon-refresh icon-refresh-animate"></div>
        </div>

        <div id="email-app"></div>

    </div>

{% endblock content %}

{% block scripts %}

    <script type="text/javascript" src='{% static "js/underscore-min-1.7.0.js" %}'></script>
    <script type="text/javascript" src='{% static "js/amplify.min.js" %}'></script>
    <script type="text/javascript" src='{% static "js/react.min.js" %}'></script>
    <script type="text/javascript" src='{% static "js/JSXTransformer.js" %}'></script>
    <script type="text/javascript" src='{% static "js/reflux.min.js" %}'></script>

    <script>
        $(document).ready(function () {
            var id_payslip_path = $('#id_payslip_path');
            var inputLoadingIcon = $('.icon-refresh-animate', '#payslip-select-form');

            var showInputLoadingIcon = function(show) {
                if (show) {
                    inputLoadingIcon.show();
                } else {
                    inputLoadingIcon.hide();
                }
            };

            var initAutoComplete = function (){
                id_payslip_path.bind( "keydown",
                    function( event ) {
                        // don't navigate away from the field on tab when selecting an item
                        if ( event.keyCode === $.ui.keyCode.TAB &&
                            $( this ).autocomplete( "instance" ).menu.active ) {
                            event.preventDefault();
                        }
                        // Enter key = update payslips table
                        if ( event.keyCode === 13 ) {
                            get_paylips_list();
                            event.preventDefault();
                        }
                    })
                    .autocomplete({
                        source: function( request, response ) {
                            showInputLoadingIcon( true );
                            $.ajax({
                                url: 'api/search/',
                                type: 'get',
                                data: {
                                    'payslip': request.term
                                }
                            }).done(function( result ) {
                                showInputLoadingIcon( false );
                                var formattedData = _.map( result.data, function( data ) {
                                    return data[ 1 ] + " [" + data[ 0 ] + "]";
                                });
                                response( formattedData );
                            });
                        },
                        focus: function() {
                            // prevent value inserted on focus
                            return false;
                        },
                        select: function( event, ui ) {
                            this.value = ui.item.value || "";
                            get_paylips_list( this.value );
                            return false;
                        }
                    }
                );
            };

            var get_paylips_list = function ( payslipId ){
                var id = payslipId ? payslipId : id_payslip_path.val();
                id = id.match(/\[(\d+)\]/);
                id = id && id[ 1 ] ? parseInt( id[ 1 ] ) : null;

                if ( id !== null ) {
                    showInputLoadingIcon( true );

                    $.ajax({
                        url: '{% url 'folder_content' %}',
                        type: 'post',
                        data: {
                            'id': id
                        }
                    }).done(function( data ) {
                        showInputLoadingIcon( false );
                        emailApp.setEmployeeList( data );
                    });
                }
            };

            // Initialize autocomplete
            initAutoComplete();
            showInputLoadingIcon( false );
        });
    </script>

    <script type="text/javascript" src='{% static "js/dist/email.js" %}'></script>

{% endblock scripts %}

isi_payslip_email/payslip/templates/payslip/logs_update_sent.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}

    <title>Payslip - Logs</title>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css">

{% endblock head %}

{% block content %}

    <div class="send-form1">
            Select Payslip:
            <select id="pid">
                <option value="">Select One</option>
                {% for p in payslip_folders %}
                    <option value="{{ p.pk }}">{{ p.name }}</option>
                {% endfor %}
            </select>
            <input type="submit"
                   value="Go"
                   id="see_reports"
                   class="btn btn-success">
    </div>
    <div style="float: right; margin-top:-2.5%;">
        <button class="btn btn-success" id="export">
            Export
        </button>
    </div>
    <br />
    <!--Upload success result-->
    <div class="col-md-6">
        <div id="upload-success" class="panel panel-success">
            <div class="status panel-heading">Uploaded</div>
            <table id="upload_tbl" class="table-hover logs_tbl">
                <thead>
                    <th>Name</th>
                    <th>Payslip File</th>
                </thead>
            </table>
        </div>
    </div>

    <!--Upload error result-->
    <div class="col-md-6">
        <div id="sent-success" class="panel panel-info">
            <div class="status panel-heading">Sent</div>
            <table id="sent_tbl" class="table-hover logs_tbl">
                <thead>
                    <th>Name</th>
                    <th>Payslip File</th>
                </thead>
            </table>
        </div>
    </div>

    <div class="col-md-6">
        <div id="sent-success" class="panel panel-warning">
            <div class="status panel-heading">Unsent</div>
            <table id="unsent_tbl" class="table-hover logs_tbl">
                <thead>
                    <th>Name</th>
                    <th>Payslip File</th>
                </thead>
            </table>
        </div>
    </div>

{% endblock content %}

{% block scripts %}
    <script>
    var logs_export_url = '{% url 'logs_upload_sent_export' %}';
    </script>
    <script type="text/javascript" src="{% static 'events.js' %}"></script>

{% endblock %}

isi_payslip_email/payslip/templates/payslip/send_payslip_message.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body style="width:100%;">
    <div style="height:300px; width:100%;">
        <img src="{{ logo_url }}" style="width:100%; height:100%;">
    </div>
    <br/>
    <section style="font-size: 20px;">
        {{ greetings|safe }} <br /><br />
        <p>{{ body_message|safe }}</p>
    </section>
    <br />
    --
    <p>
       <em>{{ disclaimer|safe }}</em>
    </p>
    --
    <br />
    <address>
      <strong>{{ company_name }}</strong><br />
        {{ company_address|safe }}<br />
        <abbr title="Website">Website: </abbr> {{ company_site }} <br />
        <abbr title="Email">Email:</abbr> {{ company_email }} <br />
        <abbr title="Phone">Tel. no.:</abbr> {{ company_phone }} <br />
    </address>

</body>
</html>

isi_payslip_email/payslip/templates/payslip/success_email_payslip.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container send-message">
        <div class="alert alert-success">
            Successfully Emailed Payslip.
        </div>
    </div>

{% endblock content %}

isi_payslip_email/payslip/templates/payslip/upload.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}

    <title>Payslip - Upload</title>

    <link rel="stylesheet" href="{% static 'css/jquery.fileupload.css' %}">

{% endblock head %}

{% block content %}

    <div class="upload-form">

        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
            <i class="glyphicon glyphicon-plus"></i>
            <span>Select Payslips (pdf) to upload</span>
            <!-- The file input field used as target for the file upload widget -->
            <input id="fileupload" type="file" name="files[]" multiple>
        </span>

        <span>
            <input id="missing-payslip-button"
                   class="btn btn-primary"
                   type="button"
                   value="Get Missing Payslips List" />
            <span id="missing-payslip-date" class="well well-sm"/>
        </span>

        <br/>
        <br/>

        <!-- The global progress bar -->
        <div id="progress" class="progress">
            <div class="progress-bar progress-bar-success"></div>
        </div>
        <!-- The container for the uploaded files -->
        <div id="files" class="files"></div>

        <div id="upload-alert" class="alert alert-success" role="alert">Upload Complete!</div>

        <br/>

        <!--Upload success result-->
        <div class="col-md-6">
            <div id="upload-success" class="panel panel-success">
                <div class="status panel-heading"></div>
                <ul class="result list-group"></ul>
            </div>
        </div>

        <!--Upload error result-->
        <div class="col-md-6">
            <div id="upload-error" class="panel panel-danger">
                <div class="status panel-heading">error</div>
                <ul class="result list-group"></ul>
            </div>
        </div>

        <!--Missing payslips list-->
        <div class="col-md-12">
            <div id="missing-payslip-list" class="panel panel-danger">
                <div class="status panel-heading">Missing Payslips:</div>
                <ul class="result list-group"></ul>
            </div>
        </div>

    </div>

{% endblock content %}

{% block scripts %}

    <script src='{% static "js/jquery.fileupload.js" %}'></script>
    <script type="text/javascript" src='{% static "js/underscore-min-1.7.0.js" %}'></script>

    <script>

        var csrfToken = "{{ csrf_token }}";

    </script>
    <script src='{% static "upload.js" %}'></script>

{% endblock scripts %}